---
# Source: longhorn/templates/default-setting.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.6.0
data:
  default-setting.yaml: |-
    backup-target: cifs://woodlandpark.brickyard.whitestar.systems/longhorn
    backup-target-credential-secret: cifs-secret
    # allow-recurring-job-while-volume-detached:
    # create-default-disk-labeled-nodes:
    default-data-path: /var/lib/longhorn/
    # replica-soft-anti-affinity:
    replica-auto-balance: best-effort
    # storage-over-provisioning-percentage:
    # storage-minimal-available-percentage:
    # upgrade-checker:
    default-replica-count: 2
    # default-data-locality:
    # default-longhorn-static-storage-class:
    # backupstore-poll-interval:
    # taint-toleration:
    # system-managed-components-node-selector:
    priority-class: longhorn-critical
    # auto-salvage:
    # auto-delete-pod-when-volume-detached-unexpectedly:
    # disable-scheduling-on-cordoned-node:
    # replica-zone-soft-anti-affinity:
    node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
    # node-drain-policy:
    # replica-replenishment-wait-interval:
    # concurrent-replica-rebuild-per-node-limit:
    # disable-revision-counter:
    # system-managed-pods-image-pull-policy:
    # allow-volume-creation-with-degraded-availability:
    # auto-cleanup-system-generated-snapshot:
    # concurrent-automatic-engine-upgrade-per-node-limit:
    # backing-image-cleanup-wait-interval:
    # backing-image-recovery-wait-interval:
    guaranteed-instance-manager-cpu: 7
    # kubernetes-cluster-autoscaler-enabled:
    orphan-auto-deletion: true
    # storage-network:
    # recurring-successful-jobs-history-limit:
    # recurring-failed-jobs-history-limit:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  rules:
    - host: longhorn.ing.k3s.brickyard.whitestar.systems
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
