---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: robusta-secrets
  namespace: robusta
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  itemPath: vaults/K3S/items/Robusta-Classic
