---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-opnsense-exporter
  labels:
    app: prometheus-opnsense-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-opnsense-exporter
  template:
    metadata:
      labels:
        app: prometheus-opnsense-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: prometheus-opnsense-exporter
          image: ghcr.io/tpaulus/opnsense-exporter:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              memory: 256Mi
              cpu: 64m
            limits:
              memory: 256Mi
              cpu: 64m
          envFrom:
            - secretRef:
                name: opnsense-creds
            - configMapRef:
                name: opnsense-config
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opnsense-config
data:
  METRICS_PORT: '8080'
  DELAY: '5'
  OPNSENSE_URL: https://10.0.10.1
  OPNSENSE_SSL_VERIFY: 'false'
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: opnsense-creds
spec:
  itemPath: vaults/K3S/items/OPNSense-Exporter
