---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-tmi-exporter
  labels:
    app: prometheus-tmi-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-tmi-exporter
  template:
    metadata:
      labels:
        app: prometheus-tmi-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9099'
    spec:
      containers:
        - name: prometheus-tmi-exporter
          image: ghcr.io/tpaulus/tmobile-internet-exporter:main
          imagePullPolicy: Always
          args: 
            - '-target=192.168.12.1'
          ports:
            - containerPort: 9099
              name: metrics
          resources:
            requests:
              memory: 256Mi
              cpu: 64m
            limits:
              memory: 256Mi
              cpu: 64m
          livenessProbe:
            tcpSocket:
              port: 9099
          readinessProbe:
            tcpSocket:
              port: 9099
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
