---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-cloudflare-origin-pull-client-cert
  namespace: traefik
spec:
  secretName: blog-cloudflare-origin-pull-client-cert
  commonName: blog.tompaulus.com
  duration: 8760h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: RSA
    size: 2048
  subject:
    organizations:
      - Paulus Family
  usages:
    - digital signature
    - key encipherment
    - client auth
  issuerRef:
    name: cloudflare-origin-pull-ca
    kind: Issuer
