apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-configmap
  namespace: netbox
data:
  # NetBox environment variables
  # More configuration can be added via: https://netbox.readthedocs.io/en/stable/configuration/optional-settings/
  ALLOWED_HOSTS: '*'
  CSRF_TRUSTED_ORIGINS: &csrf_hosts 'https://netbox.whitestar.systems https://netbox.auth-ing.k3s.whitestar.systems https://netbox.ing.k3s.whitestar.systems http://localhost http://::1 http://127.0.0.1'
  CORS_ORIGIN_WHITELIST: *csrf_hosts
  CHANGELOG_RETENTION: "90"
  DB_SSLMODE: require
  EMAIL_FROM: netbox@whitestar.systems
  EMAIL_PORT: "25"
  EMAIL_SERVER: smtp-relay.smtp-relay.svc.cluster.local
  EMAIL_TIMEOUT: "10"
  EMAIL_USERNAME: ""
  EMAIL_PASSWORD: ""
  # EXEMPT_VIEW_PERMISSIONS: ''
  # LOGIN_REQUIRED: "true"
  MEDIA_ROOT: /opt/netbox/netbox/media
  METRICS_ENABLED: "true"
  # NETBOX_USERNAME: guest
  REDIS_HOST: &redis_host netbox-redis-master.netbox.svc.cluster.local
  REDIS_CACHE_HOST: *redis_host
  REDIS_PORT: &redis_port "6379"
  REDIS_CACHE_PORT: *redis_port
  REDIS_DATABASE: "0"
  REDIS_CACHE_DATABASE: "1"
  MAINTENANCE_MODE: 'False'
  DEBUG: 'False'