apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media-pvc
  namespace: netbox
  labels:
    name: netbox-media-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
