apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-configmap
  namespace: netbox
data:
  # NetBox environment variables
  # More configuration can be added via: https://netbox.readthedocs.io/en/stable/configuration/optional-settings/
  ALLOWED_HOSTS: '*'
  CHANGELOG_RETENTION: "90"
  DB_SSLMODE: require
  EMAIL_FROM: netbox@whitestar.systems
  EMAIL_PORT: "587"
  EMAIL_SERVER: email-smtp.us-west-2.amazonaws.com:587
  EMAIL_TIMEOUT: "10"
  EMAIL_USERNAME: AKIAJ6SLTZFOHHZSTUKQ
  # EXEMPT_VIEW_PERMISSIONS: ''
  # LOGIN_REQUIRED: "true"
  MEDIA_ROOT: /opt/netbox/netbox/media
  METRICS_ENABLED: "true"
  # NETBOX_USERNAME: guest
  REDIS_HOST: &redis_host netbox-redis-master.netbox.svc.cluster.local
  REDIS_CACHE_HOST: *redis_host
  REDIS_PORT: &redis_port "6379"
  REDIS_CACHE_PORT: *redis_port
  REDIS_DATABASE: "0"
  REDIS_CACHE_DATABASE: "1"
  MAINTENANCE_MODE: 'False'
  DEBUG: 'False'