apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
  namespace: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: reloader
      app.kubernetes.io/name: reloader
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: reloader
        app.kubernetes.io/name: reloader
    spec:
      containers:
        - args:
            - '--log-level=info'
            - '--resources-to-ignore=secrets'
            - '--auto-reload-all=true'
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  divisor: '1'
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: '1'
                  resource: limits.memory
          image: ghcr.io/stakater/reloader:v1.4.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: reloader-reloader
          ports:
            - containerPort: 9090
              name: http
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext: {}
          resources:
            limits:
              memory: 100Mi
              cpu: 10m
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: reloader
