apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: relay-netpol
spec:
  podSelector:
    matchLabels:
      app: relay
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.10.16/32
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 25
  egress:
  - {}
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
spec:
  selector:
    app: relay
  ports:
    - port: 25
      targetPort: 25
  type: LoadBalancer
  externalTrafficPolicy: Local
