---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-idp
  namespace: simple-idp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: simple-idp
  template:
    metadata:
      labels:
        app: simple-idp
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: simple-idp
          image: ghcr.io/tpaulus/simple-idp:sha-d339a605ed5c33cd0f8aff16bea5011bb3c64ff8
          args:
            - --config
            - /etc/simple-idp/config.yaml
            - --http-addr
            - :8080
            - --log-format
            - json
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: CLIENT_CA_CRT
              valueFrom:
                secretKeyRef:
                  name: simple-idp-client-ca
                  key: tls.crt
            - name: OIDC_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: simple-idp-signing-key
                  key: tls.key
            - name: PAPERLESS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: simple-idp-secrets
                  key: PAPERLESS_OIDC_CLIENT_SECRET
            - name: GRAFANA_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: simple-idp-secrets
                  key: GRAFANA_OIDC_CLIENT_SECRET
            - name: ARGOCD_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: simple-idp-secrets
                  key: ARGOCD_OIDC_CLIENT_SECRET
            - name: NETBOX_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: simple-idp-secrets
                  key: NETBOX_OIDC_CLIENT_SECRET
          volumeMounts:
            - name: config
              mountPath: /etc/simple-idp
              readOnly: true
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: config
          configMap:
            name: simple-idp-config
