---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sso-paulus-family
  namespace: simple-idp
spec:
  secretName: sso-paulus-family-cert
  duration: 2160h0m0s
  dnsNames:
    - sso.paulus.family
  issuerRef:
    name: letsencrypt-cf-prod
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: verify-client-cert-if-given
  namespace: simple-idp
spec:
  clientAuth:
    secretNames:
      - simple-idp-client-ca
    clientAuthType: VerifyClientCertIfGiven
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-forwarded-cert-headers
  namespace: simple-idp
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Tls-Client-Cert: ""
      X-Forwarded-Tls-Client-Cert-Info: ""
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pass-client-cert
  namespace: simple-idp
spec:
  passTLSClientCert:
    pem: true
    info:
      subject:
        commonName: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-client-cert
  namespace: simple-idp
spec:
  chain:
    middlewares:
      - name: strip-forwarded-cert-headers
      - name: pass-client-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: simple-idp
  namespace: simple-idp
  annotations:
    external-dns.kubernetes.io/target: lfp.it.paulus.family
spec:
  entryPoints: [websecure]
  routes:
    - kind: Rule
      match: Host(`sso.paulus.family`) && Path(`/authorize`)
      middlewares:
        - name: forward-client-cert
      priority: 20
      services:
        - name: simple-idp
          port: 80
    - kind: Rule
      match: Host(`sso.paulus.family`) && (Path(`/.well-known/openid-configuration`) || Path(`/jwks.json`) || Path(`/token`) || Path(`/userinfo`) || Path(`/logout`) || Path(`/oidc/v1/end_session`) || Path(`/healthz`) || Path(`/readyz`))
      middlewares:
        - name: strip-forwarded-cert-headers
      priority: 10
      services:
        - name: simple-idp
          port: 80
  tls:
    secretName: sso-paulus-family-cert
    options:
      name: verify-client-cert-if-given
      namespace: simple-idp
