---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: simple-idp-secrets
  namespace: simple-idp
spec:
  itemPath: vaults/K3S/items/simple-idp
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: simple-idp-selfsigned
  namespace: simple-idp
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: simple-idp-signing-key
  namespace: simple-idp
spec:
  secretName: simple-idp-signing-key
  commonName: simple-idp OIDC signing key
  duration: 87600h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
  issuerRef:
    name: simple-idp-selfsigned
    kind: Issuer
