---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: [sh, -c, chown nobody:nobody /data]
          volumeMounts:
            - name: prometheus-storage-volume
              mountPath: /data
      containers:
        - name: prometheus
          image: prom/prometheus:v2.51.0
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus/
            - --storage.tsdb.retention.size=100GB
            - --storage.tsdb.retention.time=4w
            - --enable-feature=auto-gomaxprocs,new-service-discovery-manager,memory-snapshot-on-shutdown
            - --web.external-url=https://prometheus.ing.k3s.brickyard.whitestar.systems
            - --web.enable-lifecycle
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
            - name: rules-volume
              mountPath: /run/prometheus-rules
            - name: netbox-token
              mountPath: /run/secrets/netbox-token
          resources:
            requests:
              memory: 6144Mi
              cpu: 5000m
            limits:
              memory: 6144Mi
              cpu: 5000m
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
        - name: rules-git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.2.1
          args:
            - --repo=https://github.com/tpaulus/kube-config.git
            - --root=/run/prometheus-rules
            - --link=kube-config
            - --period=1m
            - --webhook-url=http://127.0.0.1:9090/-/reload
            - --webhook-method=POST
            - --http-metrics
            - --http-bind=:1234
          ports:
            - containerPort: 1234
              name: metrics
          volumeMounts:
            - name: rules-volume
              mountPath: /run/prometheus-rules
          resources:
            requests:
              memory: 256Mi
              cpu: 50m
            limits:
              memory: 512Mi
              cpu: 100m
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: tsdb
        - name: rules-volume
          emptyDir: {}
        - name: netbox-token
          secret:
            secretName: netbox-token
            items:
              - key: password
                path: netbox-token
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsdb
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 120Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
