---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-ingress-cert
spec:
  secretName: default-ingress-cert
  duration: 2160h0m0s  # 90 days
  dnsNames: ['*.ing.k3s.brickyard.whitestar.systems']
  issuerRef:
    name: letsencrypt-cf-prod
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  defaultCertificate:
    secretName: default-ingress-cert
