apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-ingress-cert
spec:
  secretName: default-ingress-cert

  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - "*.ing.k3s.brickyard.whitestar.systems"
  issuerRef:
    name: letsencrypt-cf-prod
    kind: ClusterIssuer