apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default  # This is the name it MUST be
  namespace: traefik

spec:
  defaultGeneratedCert:
    resolver: cf_wss
    domain:
      main: "ing.k3s.brickyard.whitestar.systems"
      sans:
        - "*.ing.k3s.brickyard.whitestar.systems"