---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
spec:
  resources:
    requests:
      storage: 2.5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown 472:0 /data"]
          volumeMounts:
            - name: grafana-storage-volume
              mountPath: /data
      containers:
        - name: grafana
          image: grafana/grafana:10.3.3
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: GF_LOG_LEVEL
              value: DEBUG
            - name: GF_LOG_MODE
              value: console
            - name: GF_SERVER_HTTP_PORT
              value: "3000"
            - name: GF_PATHS_CONFIG
              value: /local/grafana.ini
            - name: GF_PATHS_PROVISIONING
              value: /local/grafana/provisioning
          volumeMounts:
            - name: grafana-config
              mountPath: /local/grafana.ini
              subPath: grafana.ini
            - name: grafana-storage-volume
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /local/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-storage-volume
          persistentVolumeClaim:
            claimName: grafana
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        
