---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: home-assistant-upstream-tls@kubernetescrd
spec:
  type: ExternalName
  externalName: broadmoor.brickyard.whitestar.systems
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
