---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: homepage-config-ssh-key
  namespace: homepage
spec:
  itemPath: vaults/K3S/items/Homepage Config Deploy Key
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-api-key
  namespace: homepage
spec:
  itemPath: vaults/K3S/items/sonarr-api-key
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: radarr-api-key
  namespace: homepage
spec:
  itemPath: vaults/K3S/items/radarr-api-key
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prowlarr-api-key
  namespace: homepage
spec:
  itemPath: vaults/K3S/items/prowlarr-api-key
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bazarr-api-key
  namespace: homepage
spec:
  itemPath: vaults/K3S/items/bazarr-api-key
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: paperless-api-key
  namespace: homepage
spec:
  itemPath: vaults/K3S/items/paperless-api-key
