---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: h-snap
  namespace: longhorn-system
spec:
  cron: 0 */3 * * *
  task: snapshot
  groups: [default]
  retain: 4
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: 12h-backup
  namespace: longhorn-system
spec:
  cron: 15 */12 * * *
  task: backup
  groups: [default]
  retain: 2
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snap-cleanup
  namespace: longhorn-system
spec:
  cron: 0 2 * * *
  task: snapshot-cleanup
  groups: [default]
  retain: 0
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: fs-trim
  namespace: longhorn-system
spec:
  cron: 30 3 * * 2
  task: filesystem-trim
  groups: [default]
  retain: 0
  concurrency: 1
