---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rclone-secrets
  namespace: paperless-ngx
spec:
  itemPath: vaults/K3S/items/Paperless-RClone
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: paperless-ngx
data:
  rclone.conf: |
    [b2]
    type = b2
    hard_delete = true

    [compress-b2]
    type = compress
    remote = b2:paulus-family-paperless

    [encrypt-compress-b2]
    type = crypt
    remote = compress-b2:/
    filename_encryption = standard
    directory_name_encryption = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
  namespace: paperless-ngx
data:
  export.sh: |
    #!/bin/sh
    set -e
    BACKUP_DIR="/backup"
    
    echo "Exporting Paperless-ngx data..."
    document_exporter ${BACKUP_DIR}
    
    echo "Export completed!"

  upload.sh: |
    #!/bin/sh
    set -e
    BACKUP_DIR="/backup"
    
    echo "Uploading backup to B2"
    rclone --config /rclone-config/rclone.conf \
      sync ${BACKUP_DIR} encrypt-compress-b2:/
    
    echo "Backup uploaded to B2"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-backup
  namespace: paperless-ngx
spec:
  schedule: "37 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: backup-volume
              emptyDir: {}
            - name: data
              persistentVolumeClaim:
                claimName: paperless-ngx-data
            - name: media
              persistentVolumeClaim:
                claimName: paperless-ngx-media
            - name: backup-scripts
              configMap:
                name: backup-scripts
                defaultMode: 0744
            - name: rclone-config
              configMap:
                name: rclone-config
                defaultMode: 0744
          initContainers:
            - name: exporter
              image: ghcr.io/paperless-ngx/paperless-ngx:2.14.0
              command: ["/bin/sh", "/scripts/export.sh"]
              envFrom:
                - configMapRef:
                    name: paperless-ngx-config
                - secretRef:
                    name: app-secrets
              env:
                - name: "PAPERLESS_DBUSER"
                  valueFrom:
                    secretKeyRef:
                        key: username
                        name: db
                - name: "PAPERLESS_DBPASS"
                  valueFrom:
                    secretKeyRef:
                        key: password
                        name: db
                - name: "PAPERLESS_DBNAME"
                  valueFrom:
                    secretKeyRef:
                        key: database
                        name: db
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
                - name: backup-scripts
                  mountPath: /scripts
                - name: data
                  mountPath: /usr/src/paperless/data
                - name: media
                  mountPath: /usr/src/paperless/media
            - name: uploader
              image: rclone/rclone:1.68.2
              command: ["/bin/sh", "/scripts/upload.sh"]
              envFrom:
              - secretRef:
                  name: rclone-secrets
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
                - name: rclone-config
                  mountPath: /rclone-config
                - name: backup-scripts
                  mountPath: /scripts
          containers:
            - name: job-done
              image: busybox
              command: ['sh', '-c', 'echo "Backup completed and uploaded!"']
          restartPolicy: Never
