---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rclone-secrets
  namespace: paperless-ngx
spec:
  itemPath: vaults/K3S/items/Paperless-RClone
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: paperless-ngx
data:
  rclone.conf: |
    [b2]
    type = b2
    hard_delete = true

    [compress-b2]
    type = compress
    remote = b2:paulus-family-paperless

    [encrypt-compress-b2]
    type = crypt
    remote = compress-b2:/
    filename_encryption = standard
    directory_name_encryption = true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paperless-backup
  namespace: paperless-ngx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paperless-backup
  namespace: paperless-ngx
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paperless-backup
  namespace: paperless-ngx
subjects:
  - kind: ServiceAccount
    name: paperless-backup
    namespace: paperless-ngx
roleRef:
  kind: Role
  name: paperless-backup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
  namespace: paperless-ngx
data:
  backup.sh: |
    #!/bin/bash
    set -e
    
    NAMESPACE="paperless-ngx"
    POD_LABEL="app=paperless-ngx"
    CONTAINER="paperless-ngx"
    EXPORT_PATH="/usr/src/paperless/export"
    LOCAL_BACKUP="/backup"
    
    echo "$(date): Starting Paperless-ngx export..."
    
    POD_NAME=$(kubectl get pods -n ${NAMESPACE} -l ${POD_LABEL} -o jsonpath='{.items[0].metadata.name}')
    if [ -z "$POD_NAME" ]; then
      echo "ERROR: Could not find paperless pod"
      exit 1
    fi
    echo "Found pod: ${POD_NAME}"
    
    echo "Running document_exporter in pod..."
    kubectl exec -n ${NAMESPACE} ${POD_NAME} -c ${CONTAINER} -- \
      bash -c "rm -rf ${EXPORT_PATH}/* && document_exporter ${EXPORT_PATH}"
    
    echo "Copying export from pod..."
    kubectl cp ${NAMESPACE}/${POD_NAME}:${EXPORT_PATH} ${LOCAL_BACKUP} -c ${CONTAINER}
    
    echo "Cleaning up export in pod..."
    kubectl exec -n ${NAMESPACE} ${POD_NAME} -c ${CONTAINER} -- rm -rf ${EXPORT_PATH}/*
    
    echo "$(date): Export completed! Files in ${LOCAL_BACKUP}:"
    ls -la ${LOCAL_BACKUP}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-script
  namespace: paperless-ngx
data:
  upload.sh: |
    #!/bin/sh
    set -e
    
    echo "$(date): Uploading backup to B2..."
    rclone --config /rclone-config/rclone.conf \
      sync /backup encrypt-compress-b2:/
    
    echo "$(date): Backup uploaded to B2!"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-backup
  namespace: paperless-ngx
spec:
  schedule: "37 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: paperless-backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              emptyDir: {}
            - name: backup-scripts
              configMap:
                name: backup-scripts
                defaultMode: 0755
            - name: upload-script
              configMap:
                name: upload-script
                defaultMode: 0755
            - name: rclone-config
              configMap:
                name: rclone-config
                defaultMode: 0644
          initContainers:
            - name: exporter
              image: alpine/k8s:1.35.0
              command: ["/bin/bash", "/scripts/backup.sh"]
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
                - name: backup-scripts
                  mountPath: /scripts
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
          containers:
            - name: uploader
              image: rclone/rclone:1.72.0
              command: ["/bin/sh", "/scripts/upload.sh"]
              envFrom:
                - secretRef:
                    name: rclone-secrets
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
                - name: upload-script
                  mountPath: /scripts
                - name: rclone-config
                  mountPath: /rclone-config
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
