apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-io-datastore
  namespace: changedetection-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi