---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ghost-db
spec:
  itemPath: vaults/K3S/items/Ghost-DB
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:9.0.1
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-db
                  key: root-password
            - name: MYSQL_DATABASE
              value: ghost
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ghost-db
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-db
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: 1024Mi
              cpu: '1'
            limits:
              memory: 2048Mi
              cpu: '2'
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql


# Backup Config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "0 2,14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: storage
              nfs:
                server: woodlandpark.brickyard.whitestar.systems
                path: "/mnt/tank/Server Backups/db-dumps"
                readOnly: false
          containers:
          - name: mysql-backup
            image: mysql:9.0.1
            volumeMounts:
            - name: storage
              mountPath: /backup
            env:
            - name: MYSQL_DATABASE
              value: "ghost"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghost-db
                  key: root-password
            - name: MYSQL_HOST
              value: mysql.blog.svc
            command:
            - sh
            - -c
            - |
              mkdir -p /backup/${MYSQL_DATABASE}
              mysqldump --user="root" --host="${MYSQL_HOST}" --password="${MYSQL_ROOT_PASSWORD}" "${MYSQL_DATABASE}" > /backup/${MYSQL_DATABASE}/backup_$(date +%Y%m%d%H%M%S).sql
              
              # Retain last 7 backups
              ls -t /backup/${MYSQL_DATABASE}/backup_*.sql | tail -n +8 | xargs -r rm
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false