---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: inject-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blog-public
  annotations:
    external-dns.kubernetes.io/target: lfp.it.paulus.family
    external-dns.kubernetes.io/cloudflare-proxied: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`blog.tompaulus.com`) && !PathPrefix(`/ghost`) && !PathPrefix(`/members/api`)
      kind: Rule
      services:
        - name: ghost
          port: 2368
      middlewares:
        - name: inject-headers
          namespace: blog
  tls:
    secretName: blog-tompaulus-com-cert
    options:
      name: require-cloudflare-origin-pull
      namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blog-internal
spec:
  entryPoints:
    - web-mtls
  routes:
    - match: Host(`blog.tompaulus.com`) && (PathPrefix(`/ghost`) || PathPrefix(`/members/api`))
      kind: Rule
      services:
        - name: ghost
          port: 2368
      middlewares:
        - name: inject-headers
          namespace: blog
  tls:
    secretName: blog-tompaulus-com-cert
    options:
      name: require-client-cert
      namespace: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-tompaulus-com-cert
spec:
  secretName: blog-tompaulus-com-cert
  duration: 2160h0m0s
  dnsNames:
    - blog.tompaulus.com
  issuerRef:
    name: letsencrypt-cf-prod
    kind: ClusterIssuer
