apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.ing.k3s.brickyard.whitestar.systems`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.ing.k3s.brickyard.whitestar.systems`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jwt-verification
  namespace: argocd
spec:
  plugin:
    jwt:
      issuers:
        - https://whitestar.cloudflareaccess.com/cdn-cgi/access/certs
      headerName: 'Cf-Access-Jwt-Assertion'
      require:
        aud: f2d6259e0bc9268137d8382a2b145834130153c17ddefae081fa8e4c60603998
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ext
  namespace: argocd
spec:
  entryPoints:
    - web-ext
  routes:
    - kind: Rule
      match: Host(`argocd.auth-ing.k3s.brickyard.whitestar.systems`)
      middlewares:
      - name: jwt-verification
        namespace: argocd
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.auth-ing.k3s.brickyard.whitestar.systems`) && Headers(`Content-Type`, `application/grpc`)
      middlewares:
      - name: jwt-verification
        namespace: argocd
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
