---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  admin_user: admin
  admin_password_secret: awx-secrets
  secret_key_secret: awx-secrets
  service_type: ClusterIP
  ingress_type: ingress
  ingress_class_name: traefik
  ingress_hosts:
    - hostname: awx.ing.k3s.brickyard.whitestar.systems
  postgres_data_volume_init: true
  postgres_storage_requirements:
    requests:
      storage: 8Gi
