---
# The 1Password item should expose `password`, `secret_key`, `vault_password`,
# and `netbox_token` fields.
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: awx-secrets
  namespace: awx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: vaults/K3S/items/awx
