---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ha-cert
spec:
  secretName: ha-cert
  duration: 2160h0m0s
  dnsNames: ['home.paulus.family']
  issuerRef:
    name: letsencrypt-cf-prod
    kind: ClusterIssuer
