---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  type: ExternalName
  externalName: woodlandpark.brickyard.whitestar.systems
  ports:
    - name: http
      protocol: TCP
      port: 30013
      targetPort: 30013
