---
apiVersion: v1
kind: Namespace
metadata:
  name: backup-unifi-protect
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-protect-backup-sqllite
  namespace: backup-unifi-protect
  uid: abd885ff-9ba8-4d65-8df3-d1c29510cd7b
spec:
  resources:
    requests:
      storage: 2.5Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  volumeName: pvc-d84f5c73-a129-4866-bb5d-10dcff58b493
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-unifi-protect
  namespace: backup-unifi-protect
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backup-unifi-protect
  template:
    metadata:
      labels:
        app: backup-unifi-protect
    spec:
      containers:
        - name: unifi-protect-backup
          image: ghcr.io/ep1cman/unifi-protect-backup:0.13.0
          resources:
            requests:
              memory: 1024Mi
              cpu: 1024m
            limits:
              memory: 2048Mi
              cpu: 2048m
          env:
            - name: SQLITE_PATH
              value: /data/backup-events
          envFrom:
            - configMapRef:
                name: protect-config
            - configMapRef:
                name: rclone-args
            - secretRef:
                name: rclone-secrets
            - secretRef:
                name: protect-secrets
          volumeMounts:
            - name: unifi-protect-backup-nfs-volume
              mountPath: /data
            - name: rclone-config
              mountPath: /config/rclone
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: unifi-protect-backup-nfs-volume
          persistentVolumeClaim:
            claimName: unifi-protect-backup-sqllite
        - name: rclone-config
          configMap:
            name: rclone-config
            items:
              - key: rclone.conf
                path: rclone.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: backup-unifi-protect
data:
  rclone.conf: |
    [b2]
    type = b2
    hard_delete = true
    [compress-b2]
    type = compress
    remote = b2:seaview-protect
    [encrypt-compress-b2]
    type = crypt
    remote = compress-b2:/
    filename_encryption = off
    directory_name_encryption = false
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rclone-secrets
  namespace: backup-unifi-protect
spec:
  itemPath: vaults/K3S/items/Protect-Backup-RClone
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-args
  namespace: backup-unifi-protect
data:
  RCLONE_RETENTION: 3d
  RCLONE_DESTINATION: encrypt-compress-b2:/
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: protect-secrets
  namespace: backup-unifi-protect
spec:
  itemPath: vaults/K3S/items/Protect-Backup-Protect
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: protect-config
  namespace: backup-unifi-protect
data:
  UFP_SSL_VERIFY: 'false'
  EXPERIMENTAL_DOWNLOADER: 'true'
