---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
    directory:
      recurse: true
  ignoreDifferences:
    - group: traefik.io
      kind: Middleware
      name: github-webhook-ip-allowlist
      namespace: argocd
      jsonPointers:
        - /spec/ipAllowList/sourceRange
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - RespectIgnoreDifferences=true
