apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
spec:
  destination:
    name: ''
    namespace: authentik
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.goauthentik.io'
    targetRevision: 2024.2.2
    chart: authentik
    helm:
      values: |-
        {
            "authentik": {
                "email": {
                    "host": "smtp-relay.smtp-relay.svc.cluster.local",
                    "port": 25,
                    "from": "authentik@whitestar.systems"
                }
            },

            "server": {
                "ingress": {
                    "annotations": {
                        "traefik.ingress.kubernetes.io/router.entrypoints": "web-ext",
                        "traefik.ingress.kubernetes.io/router.middlewares": "authentik-inject-headers@kubernetescrd"
                    },
                    "enabled": true,
                    "hosts": [
                        "authentik.auth-ing.k3s.brickyard.whitestar.systems",
                        "auth.whitestar.systems"
                    ]
                },
                "metrics": {
                    "enabled": true
                }
            },

            "postgres": {
                "enabled": false
            },

            "redis": {
                "enabled": true
            },

            "global": {
                "addPrometheusAnnotations": true,
                "env": [
                    {
                        "name": "AUTHENTIK_POSTGRESQL__HOST",
                        "valueFrom": {
                            "secretKeyRef": {
                                "name": "authentik-pguser-authentik",
                                "key": "host"
                            }
                        }
                    },
                    {
                        "name": "AUTHENTIK_POSTGRESQL__NAME",
                        "valueFrom": {
                            "secretKeyRef": {
                                "name": "authentik-pguser-authentik",
                                "key": "dbname"
                            }
                        }
                    },
                    {
                        "name": "AUTHENTIK_POSTGRESQL__USER",
                        "valueFrom": {
                            "secretKeyRef": {
                                "name": "authentik-pguser-authentik",
                                "key": "user"
                            }
                        }
                    },
                     {
                        "name": "AUTHENTIK_POSTGRESQL__PORT",
                        "valueFrom": {
                            "secretKeyRef": {
                                "name": "authentik-pguser-authentik",
                                "key": "port"
                            }
                        }
                    },
                    {
                        "name": "AUTHENTIK_POSTGRESQL__PASSWORD",
                        "valueFrom": {
                            "secretKeyRef": {
                                "name": "authentik-pguser-authentik",
                                "key": "password"
                            }
                        }
                    },
                    {
                        "name": "AUTHENTIK_POSTGRESQL__SSLMODE",
                        "value": "require"
                    },
                    {
                        "name": "AUTHENTIK_POSTGRESQL__SSLROOTCERT",
                        "value": "/etc/ssl/postgres/ca.crt"
                    },
                    {
                        "name": "AUTHENTIK_POSTGRESQL__SSLCERT",
                        "value": "/etc/ssl/postgres/tls.crt"
                    },
                    {
                        "name": "AUTHENTIK_POSTGRESQL__SSLKEY",
                        "value": "/etc/ssl/postgres/tls.key"
                    }
                ],
                "envFrom": [
                    {
                        "secretRef": {
                            "name": "authentik-secret"
                        }
                    }
                ],
                "securityContext": {
                  "fsGroup": 1000
                },

                "volumeMounts": [
                    {
                      "name": "db-cert",
                      "mountPath": "/etc/ssl/postgres"
                    }
                ],

                "volumes": [
                    {
                      "name": "db-cert",
                      "secret": {
                        "secretName": "authentik-cluster-cert",
                        "items": [
                          {
                            "key": "tls.crt",
                            "path": "tls.crt",
                            "mode": 0o775
                          },
                          {
                            "key": "tls.key",
                            "path": "tls.key",
                            "mode": 0o640
                          },
                          {
                            "key": "ca.crt",
                            "path": "postgresql.crt",
                            "mode": 0o775
                          }
                        ]
                      }
                    }
                  ]
            },
            "geoip": {
                "enabled": false
            },
            "additionalObjects": [
              {
                "apiVersion": "postgres-operator.crunchydata.com/v1beta1",
                "kind": "PostgresCluster",
                "metadata": {
                  "name": "authentik",
                  "namespace": "authentik"
                },
                "spec": {
                  "image": "registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.5-0",
                  "postgresVersion": 15,
                  "instances": [
                    {
                      "name": "authentik-primary",
                      "dataVolumeClaimSpec": {
                        "accessModes": [
                          "ReadWriteOnce"
                        ],
                        "resources": {
                          "requests": {
                            "storage": "5Gi"
                          }
                        }
                      }
                    }
                  ],
                  "users": [
                    {
                      "databases": [
                        "authentik"
                      ],
                      "name": "authentik",
                      "options": "SUPERUSER"
                    }
                  ],
                  "backups": {
                    "pgbackrest": {
                      "image": "registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-2",
                      "repos": [
                        {
                          "name": "repo1",
                          "volume": {
                            "volumeClaimSpec": {
                              "accessModes": [
                                "ReadWriteOnce"
                              ],
                              "resources": {
                                "requests": {
                                  "storage": "5Gi"
                                }
                              }
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              },
              {
                "apiVersion": "onepassword.com/v1",
                "kind": "OnePasswordItem",
                "metadata": {
                  "name": "authentik-secret",
                  "namespace": "authentik"
                },
                "spec": {
                  "itemPath": "vaults/K3S/items/authentik"
                }
              },
              {
                "apiVersion": "traefik.io/v1alpha1",
                "kind": "Middleware",
                "metadata": {
                  "name": "inject-headers"
                },
                "spec": {
                  "headers": {
                    "customRequestHeaders": {
                      "X-Forwarded-Proto": "https"
                    }
                  }
                }
              }
            ]
        }
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
