---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backup-unifi-protect
  namespace: argocd
spec:
  destination:
    namespace: backup-unifi-protect
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backup-unifi-protect
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
