---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
        - name: enableCertificateOwnerRef
          value: 'true'
        - name: clusterResourceNamespace
          value: 'cert-manager'
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.3
  syncPolicy:
    automated:
      prune: true
    syncOptions: [CreateNamespace=true]
