---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coa-utility-bill-generator
  namespace: argocd
spec:
  destination:
    namespace: coa-utility-bill-generator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: coa-utility-bill-generator
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
