---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-records
  namespace: argocd
spec:
  destination:
    namespace: external-records
    server: https://kubernetes.default.svc
  project: default
  source:
    path: external-records
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
    directory:
      jsonnet:
        libs:
          - lib
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
