---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-sync
  namespace: argocd
spec:
  destination:
    namespace: external-dns-sync
    server: https://kubernetes.default.svc
  project: default
  source:
    path: external-dns-sync
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true