---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-sync
  namespace: argocd
spec:
  project: default
  sources:
    - path: external-dns-sync
      repoURL: git@github.com:tpaulus/kube-config.git
      targetRevision: HEAD
    - path: config/crd/standard
      repoURL: https://github.com/kubernetes-sigs/external-dns.git
      targetRevision: master
      directory:
        include: '{dnsendpoints.externaldns.k8s.io.yaml,dnsrecords.externaldns.k8s.io.yaml}'
  destination:
    namespace: external-dns-sync
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true