---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kured
      repoURL: https://kubereboot.github.io/charts
      targetRevision: 5.9.0
      helm:
        values: |
          configuration:
            notifyUrl: smtp://smtp-relay.smtp-relay.svc.cluster.local:25/?fromAddress=kured@whitestar.systems&toAddresses=ops@whitestar.systems
            annotateNodes: true
            prometheusUrl: 'http://prometheus.monitoring.svc.cluster.local:8080'
            alertFilterRegexp: '^RebootRequired$'
          service:
            create: true
            annotations:
              prometheus.io/scrape: 'true'
              prometheus.io/port: '8080'
  destination:
    server: https://kubernetes.default.svc
    namespace: kured
  syncPolicy:
    automated:
      prune: true
    syncOptions: [CreateNamespace=true]
