---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured-alert-silencer
  namespace: argocd
spec:
  destination:
    namespace: kured
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kured-alert-silencer
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
