---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - chart: loki
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.27.0
      helm:
        values: |
          deploymentMode: SingleBinary
          loki:
            auth_enabled: false
            commonConfig:
              replication_factor: 1
            schemaConfig:
              configs:
                - from: "2024-01-01"
                  store: tsdb
                  object_store: filesystem
                  schema: v13
                  index:
                    prefix: index_
                    period: 24h
            storage:
              type: filesystem
            limits_config:
              retention_period: 168h  # 7 days
              ingestion_rate_mb: 4
              ingestion_burst_size_mb: 6
          singleBinary:
            replicas: 1
            persistence:
              enabled: true
              size: 10Gi
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
          # Disable components not needed for SingleBinary mode
          backend:
            replicas: 0
          read:
            replicas: 0
          write:
            replicas: 0
          gateway:
            enabled: false
          # Disable test pod
          test:
            enabled: false
          # Disable self-monitoring
          lokiCanary:
            enabled: false
          # Chunk cache (optional, helps performance)
          chunksCache:
            enabled: false
          resultsCache:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
