---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.9.0  # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            backupTargetCredentialSecret: cifs://woodlandpark.brickyard.whitestar.systems/longhorn
            backupTargetCredentialSecret: cifs-secret
            defaultDataPath: /var/lib/longhorn/
            replicaAutoBalance: best-effort
            defaultReplicaCount: 2
            priorityClass: longhorn-critical
            v2DataEngineGuaranteedInstanceManagerCPU: 7
          ingress:
            enabled: true
            host: longhorn.ing.k3s.brickyard.whitestar.systems
          longhornManager:
            serviceAnnotations:
              prometheus.io/scrape: 'true'
              prometheus.io/port:   '9500'
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
