---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-deps
  namespace: argocd
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: longhorn-deps
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
