---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: ''
    namespace: metallb
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://metallb.github.io/metallb'
    targetRevision: 0.14.4
    chart: metallb
  sources: []
  project: default

