---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://metallb.github.io/metallb'
    targetRevision: 0.14.9
    helm:
      parameters:
        - name: prometheus.namespace
          value: monitoring
        - name: prometheus.scrapeAnnotations
          value: 'true'
      values: |
        speaker:
          podAnnotations:
            prometheus.io/port: '7472'
    chart: metallb
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: "CustomResourceDefinition"
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
  project: default
  syncPolicy:
    managedNamespaceMetadata:
       labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true