---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-exporters
  namespace: argocd
spec:
  destination:
    namespace: metrics-exporters
    server: https://kubernetes.default.svc
  project: default
  source:
    path: metrics-exporters
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
