---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  destination:
    namespace: postgres
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pgo
    repoURL: registry.developers.crunchydata.com/crunchydata
    targetRevision: 5.5.1
  syncPolicy:
    automated:
      prune: true
    syncOptions: [ServerSideApply=true]
