---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
spec:
  destination:
    namespace: reloader
    server: https://kubernetes.default.svc
  source:
    path: reloader
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions: [CreateNamespace=true]