---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
spec:
  destination:
    namespace: reloader
    server: https://kubernetes.default.svc
  source:
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.2.0
    chart: reloader
    helm:
      parameters:
        - name: reloader.ignoreSecrets
          value: 'true'  # The 1P CRD does this for us
        - name: reloader.autoReloadAll
          value: 'true'
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions: [CreateNamespace=true]