---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    helm:
      parameters:
        - name: deployment.replicas
          value: "2"
      values: |
        ports:
          web:
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
                  permanent: true
          websecure:
            asDefault: true
          web-mtls:
            asDefault: true
            port: 9443
            exposedPort: 9443
            expose:
              default: true
            protocol: TCP
            http:
              tls:
                enabled: true
                options: traefik-require-client-cert@kubernetescrd
        accessLog:
          enabled: true
          format: json
          filters:
            statusCodes: 400-599
          fields:
            headers:
              defaultMode: drop
              names:
                CF-Connecting-IP: keep
                CF-Ray: keep
                User-Agent: keep
                X-Forwarded-For: keep
                X-Forwarded-Proto: keep
        experimental:
          plugins:
            fail2ban:
              moduleName: github.com/tomMoulard/fail2ban
              version: v0.9.0
        providers:
          kubernetesIngress:
            allowExternalNameServices: true
            publishedService:
              enabled: true
        service:
          spec:
            externalTrafficPolicy: Local
    repoURL: https://traefik.github.io/charts
    targetRevision: 41.5.0
  syncPolicy:
    automated:
      prune: true
    syncOptions: [CreateNamespace=true]
