---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    helm:
      parameters:
        - name: deployment.replicas
          value: '2'
      values: |
        experimental.plugins.enabled: true
        ports:
          web:
            redirectTo:
              port: websecure
              priority: 1
          websecure:
            asDefault: true
          web-ext:
            port: 9200
            exposedPort: 9200
            protocol: TCP
            middlewares:
              - traefik-rewrite-cf-tunnel-headers@kubernetescrd
        experimental:
          plugins:
            jwt:
              moduleName: github.com/tpaulus/jwt-middleware
              version: v1.1.13
            cloudflarewarp:
              moduleName: github.com/BetterCorp/cloudflarewarp
              version: v1.3.0
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
    repoURL: https://traefik.github.io/charts
    targetRevision: 31.0.0
  syncPolicy:
    automated:
      prune: true
    syncOptions: [CreateNamespace=true]
