---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel-deps
  namespace: argocd
spec:
  destination:
    namespace: zitadel
    server: https://kubernetes.default.svc
  project: default
  source:
    path: zitadel-deps
    repoURL: git@github.com:tpaulus/kube-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
