---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
spec:
  destination:
    namespace: zitadel
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.zitadel.com
    targetRevision: 8.13.3
    chart: zitadel
    helm:
      values: |
        zitadel:
          masterkeySecretName: "zitadel"
          configmapConfig:
            ExternalPort: 443
            ExternalSecure: true
            ExternalDomain: "auth.whitestar.systems"
            TLS:
              Enabled: false
          
            Database:
              Postgres:
                MaxOpenConns: 20
                MaxIdleConns: 10
                MaxConnLifetime: 30m
                MaxConnIdleTime: 5m
                User:
                  SSL:
                    Mode: disable
                Admin:
                  SSL:
                    Mode: disable
            
        env:
          - name: "ZITADEL_DATABASE_POSTGRES_HOST"
            value: db.zitadel.svc
          - name: "ZITADEL_DATABASE_POSTGRES_PORT"
            value: "5432"
          - name: "ZITADEL_DATABASE_POSTGRES_DATABASE"
            valueFrom:
              secretKeyRef:
                name: db
                key: database
          - name: "ZITADEL_DATABASE_POSTGRES_USER_USERNAME"
            valueFrom:
              secretKeyRef:
                name: db
                key: username
          - name: "ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME"
            valueFrom:
              secretKeyRef:
                name: db
                key: username
          - name: "ZITADEL_DATABASE_POSTGRES_USER_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db
                key: password
          - name: "ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: db
                key: password
        service:
          annotations:
            traefik.ingress.kubernetes.io/service.serversscheme: h2c
        ingress:
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web-ext
            traefik.ingress.kubernetes.io/router.middlewares: zitadel-inject-headers@kubernetescrd
          enabled: true
          hosts:
            - host: zitadel.auth-ing.k3s.brickyard.whitestar.systems
              paths: 
                - path: "/"
                  pathType: Prefix
            - host: auth.whitestar.systems
              paths: 
                - path: "/"
                  pathType: Prefix
        metrics:
          enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
