apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
spec:
  destination:
    name: ''
    namespace: zitadel
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.zitadel.com'
    targetRevision: 7.9.1
    chart: zitadel
    helm:
      values: |
        zitadel:
          masterkeySecretName: "zitadel"
          dbSslCaCrtSecret: &db_cert_secret zitadel-db-cluster-cert
          dbSslUserCrtSecret: *db_cert_secret

          configmapConfig:
            ExternalSecure: true
            ExternalDomain: "auth.whitestar.systems"
            TLS:
              Enabled: false
          
            Database:
              Postgres:
                MaxOpenConns: 20
                MaxIdleConns: 10
                MaxConnLifetime: 30m
                MaxConnIdleTime: 5m
                User:
                  SSL:
                    Mode: require
                Admin:
                  SSL:
                    Mode: require
            
        env:
          - name: "ZITADEL_DATABASE_POSTGRES_HOST"
            valueFrom:
              secretKeyRef:
                name: zitadel-db-pguser-zitadel
                key: host
          - name: "ZITADEL_DATABASE_POSTGRES_PORT"
            valueFrom:
              secretKeyRef:
                name: zitadel-db-pguser-zitadel
                key: port
          - name: "ZITADEL_DATABASE_POSTGRES_DATABASE"
            valueFrom:
              secretKeyRef:
                name: zitadel-db-pguser-zitadel
                key: dbname
          - name: "ZITADEL_DATABASE_POSTGRES_USER_USERNAME"
            valueFrom:
              secretKeyRef:
                name: zitadel-db-pguser-zitadel
                key: user
          - name: "ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME"
            valueFrom:
              secretKeyRef:
                name: zitadel-db-pguser-zitadel
                key: user
          - name: "ZITADEL_DATABASE_POSTGRES_USER_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: zitadel-db-pguser-zitadel
                key: password
          - name: "ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: zitadel-db-pguser-zitadel
                key: password

        service:
          annotations:
            traefik.ingress.kubernetes.io/service.serversscheme: h2c

        ingress:
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web-ext
            traefik.ingress.kubernetes.io/router.middlewares: zitadel-inject-headers@kubernetescrd
          enabled: true
          hosts:
            - host: zitadel.auth-ing.k3s.brickyard.whitestar.systems
              paths: 
                - path: "/"
                  pathType: Prefix
            - host: auth.whitestar.systems
              paths: 
                - path: "/"
                  pathType: Prefix

        metrics:
          enabled: true

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true