apiVersion: apps/v1
kind: Deployment
metadata:
  name: kured-alert-silencer
  namespace: kured
  labels:
    app.kubernetes.io/name: kured-alert-silencer
    app.kubernetes.io/component: alert-silencer
    app.kubernetes.io/part-of: kured
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kured-alert-silencer
      app.kubernetes.io/component: alert-silencer
      app.kubernetes.io/part-of: kured
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kured-alert-silencer
        app.kubernetes.io/component: alert-silencer
        app.kubernetes.io/part-of: kured
    spec:
      serviceAccountName: kured-alert-silencer
      restartPolicy: Always
      containers:
        - name: kured-alert-silencer
          image: ghcr.io/trustyou/kured-alert-silencer:0.0.11
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          imagePullPolicy: IfNotPresent
          command:
            - /usr/bin/kured-alert-silencer
            - --log-level=debug
            - --alertmanager-url=http://alertmanager.monitoring.svc.cluster.local:8080
            - --ds-name=kured
            - --ds-namespace=kured
            - --silence-duration=20m
            - >-
             --silence-matchers-json=[{"name": "instance", "value": "{{.NodeName}}","isRegex": false}]