---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kured-alert-silencer
  namespace: kured
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kured
  name: kured-alert-silencer
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    resourceNames: ["kured"]
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kured
  name: kured-alert-silencer
subjects:
  - kind: ServiceAccount
    namespace: kured
    name: kured-alert-silencer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kured-alert-silencer