---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: zitadel
  namespace: zitadel
spec:
  itemPath: vaults/K3S/items/zitadel
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: zitadel-selfsigned
  namespace: zitadel
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zitadel-login-service-key
  namespace: zitadel
spec:
  secretName: zitadel-login-service-key
  commonName: login-client
  duration: 87600h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - client auth
  issuerRef:
    name: zitadel-selfsigned
    kind: Issuer
