---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: next-century
spec:
  schedule: "0 10 2 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-bill
            image: ghcr.io/tpaulus/nextcentury-payhoa:main

            env:
              - name: TZ
                value: "America/Los_Angeles"
              - name: SMTP_SERVER
                value: smtp-relay.smtp-relay.svc.cluster.local
              - name: SMTP_USERNAME
                value: ""
              - name: SMTP_PASSWORD
                value: ""
              - name: SMTP_PORT
                value: "25"
              
            envFrom:
              - secretRef:
                  name: bill-generation-secrets

            resources:
              requests:
                memory: "256Mi"
                cpu: "500m"
              limits:
                memory: "256Mi"
                cpu: "500m"

          restartPolicy: OnFailure
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bill-generation-secrets
spec:
  itemPath: "vaults/K3S/items/coa-utilities-bill-generation"