apiVersion: v1
kind: Namespace
metadata:
  name: offset-tracker
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: offset-config
  namespace: offset-tracker
spec:
  itemPath: "vaults/K3S/items/Offset-Tracker"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: monarch-offset-tracker
  namespace: offset-tracker
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: monarch-offset-tracker
        spec:
          restartPolicy: OnFailure
          containers:
          - name: lunchmoney-offsets
            image: ghcr.io/tpaulus/monarch-offset-tracker:main
            resources:
              requests:
                memory: "256Mi"
                cpu: "500m"
            envFrom:
              - secretRef:
                  name: offset-config
          imagePullSecrets:
          - name: ghcr-pull-secret