---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cf-prod
spec:
  acme:
    email: admin@whitestar.systems
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cf-acme-secret
              key: api-token
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cf-acme-secret
spec:
  itemPath: vaults/K3S/items/CF-ACME
