---
apiVersion: v1
kind: Namespace
metadata:
  name: vlmcsd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlmcsd
  namespace: vlmcsd
  labels:
    app: vlmcsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlmcsd
  template:
    metadata:
      labels:
        app: vlmcsd
    spec:
      containers:
        - name: vlmcsd
          image: mikolatero/vlmcsd:latest
          resources:
            requests:
              memory: 1024Mi
              cpu: 1024m
            limits:
              memory: 1024Mi
              cpu: 1024m
          ports:
            - containerPort: 1688
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            runAsGroup: 65534
---
apiVersion: v1
kind: Service
metadata:
  name: vlmcsd
  namespace: vlmcsd
  labels:
    app: vlmcsd
spec:
  selector:
    app: vlmcsd
  ports:
    - protocol: TCP
      port: 1688
      targetPort: 1688
  type: LoadBalancer
