---
name: pint
on:
  push:
    branches: [main]
    paths: [_alerts/**]
  pull_request:
    branches: [main]
    paths: [_alerts/**]
permissions:
  pull-requests: write
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - name: Run pint
        uses: prymitive/pint-action@e3cb392fd382a69706e37b6437935bca45c0cf58 # v1.110
        with:
          token: ${{ github.token }}
        env:
          WORKDIR: _alerts/
          PINT_BRICKYARD_CLIENT_ID: ${{ secrets.PINT_BRICKYARD_CLIENT_ID }}
          PINT_BRICKYARD_CLIENT_SECRET: ${{ secrets.PINT_BRICKYARD_CLIENT_SECRET }}
